// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOuQbhoHPDLhSHbyQXhQ5uINGcQDhepUE',
    appId: '1:825311018813:web:193940a7abcd38be4e4f54',
    messagingSenderId: '825311018813',
    projectId: 'evently-online-c19-35aae',
    authDomain: 'evently-online-c19-35aae.firebaseapp.com',
    storageBucket: 'evently-online-c19-35aae.firebasestorage.app',
    measurementId: 'G-P4XTK7TS90',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoak-GTq1y45AioR-HMqAB8mhzoqSTpyg',
    appId: '1:825311018813:android:b256d0bc67a392434e4f54',
    messagingSenderId: '825311018813',
    projectId: 'evently-online-c19-35aae',
    storageBucket: 'evently-online-c19-35aae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUk1ovvuS2AlSCnbs77fRZiZur4-6W_R4',
    appId: '1:825311018813:ios:eb1f67a718f262a84e4f54',
    messagingSenderId: '825311018813',
    projectId: 'evently-online-c19-35aae',
    storageBucket: 'evently-online-c19-35aae.firebasestorage.app',
    iosBundleId: 'com.example.eventlyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUk1ovvuS2AlSCnbs77fRZiZur4-6W_R4',
    appId: '1:825311018813:ios:eb1f67a718f262a84e4f54',
    messagingSenderId: '825311018813',
    projectId: 'evently-online-c19-35aae',
    storageBucket: 'evently-online-c19-35aae.firebasestorage.app',
    iosBundleId: 'com.example.eventlyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOuQbhoHPDLhSHbyQXhQ5uINGcQDhepUE',
    appId: '1:825311018813:web:795a3512d60405164e4f54',
    messagingSenderId: '825311018813',
    projectId: 'evently-online-c19-35aae',
    authDomain: 'evently-online-c19-35aae.firebaseapp.com',
    storageBucket: 'evently-online-c19-35aae.firebasestorage.app',
    measurementId: 'G-8MTGK9T9E5',
  );
}
